version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: wdh-app:1.0.0
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - cache
    env_file:
      - .env
    networks:
      - webdimensions
  cache:
    container_name: cache
    image: redis:7.0
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    ports:
      - ${REDIS_PORT}:6379
    env_file:
      - .env
    volumes:
      - cache:/data
    networks:
      - webdimensions

volumes:
  cache:
    driver: local

networks:
  webdimensions:
    driver: bridge
