import Joi from 'joi';

export const validationSchema = Joi.object({
  PORT: Joi.number().required(),
  FRONTEND_URL: Joi.string().required(),
  POSTGRES_USER: Joi.string().required(),
  POSTGRES_PASSWORD: Joi.string().required(),
  POSTGRES_DB: Joi.string().required(),
  POSTGRES_HOST: Joi.string().required(),
  POSTGRES_PORT: Joi.number().required(),
  DATABASE_URL: Joi.string().required(),
  REDIS_USER: Joi.string().required(),
  REDIS_PASSWORD: Joi.string().required(),
  REDIS_HOST: Joi.string().required(),
  REDIS_PORT: Joi.number().required(),
  REDIS_URL: Joi.string().required(),
  ACCESS_TOKEN_EXPIRES_IN: Joi.number().required(),
  REFRESH_TOKEN_EXPIRES_IN: Joi.number().required(),
  CHANGE_EMAIL_TOKEN_EXPIRES_IN: Joi.number().required(),
  RESET_PASSWORD_TOKEN_EXPIRES_IN: Joi.number().required(),
  DELETE_ACCOUNT_TOKEN_EXPIRES_IN: Joi.number().required(),
  ACCESS_TOKEN_SECRET: Joi.string().required(),
  REFRESH_TOKEN_SECRET: Joi.string().required(),
  CHANGE_EMAIL_TOKEN_SECRET: Joi.string().required(),
  RESET_PASSWORD_TOKEN_SECRET: Joi.string().required(),
  DELETE_ACCOUNT_TOKEN_SECRET: Joi.string().required(),
  EMAIL_SERVICE: Joi.string().required(),
  EMAIL_USER: Joi.string().required(),
  EMAIL_PASSWORD: Joi.string().required(),
  AWS_ACCESS_KEY: Joi.string().required(),
  AWS_SECRET: Joi.string().required(),
  AWS_S3_REGION: Joi.string().required(),
  AWS_CLOUDFRONT_URL: Joi.string().required(),
});
